Risk analysis SCA Debug

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -523,9 +523,9 @@ jobs:
             echo "$line_number"
             echo "$issue_text"
             case $(echo "$severity") in
-              "HIGH") sev=3; echo "case1"; ((COUNT_HIGH++)) ;;
-              "MEDIUM") sev=2; echo "case2"; ((COUNT_MEDIUM++)) ;;
-              "LOW") sev=1; echo "case3"; ((COUNT_LOW++)) ;;
+              "HIGH") sev=3; echo "case1"; ((COUNT_HIGH++)) || echo "::error:: Failed incrementing high" ;;
+              "MEDIUM") sev=2; echo "case2"; ((COUNT_MEDIUM++)) || echo "::error:: Failed incrementing medium" ;;
+              "LOW") sev=1; echo "case3"; ((COUNT_LOW++)) || echo "::error:: Failed incrementing low" ;;
               *) sev=0 ;;
             esac
             echo "Debug 5"
